;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        kill-region
        paredit-backward
        paredit-backward-kill-word
        paredit-forward
        slime-space
        ))

(setq mc/cmds-to-run-once
      '(
        org-todo
        org-toggle-time-stamp-overlays
        ))
