(deftheme dark-night-gray
  "Created 2014-06-26.")

(let ((class '((class color) (min-colors 89))))
 (custom-theme-set-faces
  'dark-night-gray
  ;; '(default ((t (:background "#292424" :foreground "#b1b1b1"))))
  '(default ((t (:background "#292424" :foreground "gray90"))))
  '(fringe ((t (:background "#373333"  :foreground "#838383"))))
  '(isearch ((t (:background "magenta3" :foreground "lightskyblue1"))))
  '(lazy-highlight ((t (:background "paleturquoise" :distant-foreground "black"))))
  '(link ((t (:foreground "CadetBlue3" :underline t))))
  '(link-visited ((t (:foreground "magenta4" :underline t))))
  '(header-line ((t (:background "grey90" :foreground "grey20" :box nil))))
  '(cursor ((t (:background "yellow" :foreground "white"))))
  '(region ((t (:background "dark slate gray" :distant-foreground "gray14"))))
  '(mode-line ((t (:background "grey70" :foreground "black" :box (:line-width -1 :style released-button)))))
  '(mode-line-inactive ((t (:background "grey30" :foreground "grey80" :box (:line-width -1 :style pressed-button)))))
  '(wg-mode-line-face ((t (:foreground "dark cyan"))))
  '(minibuffer-prompt ((t (:foreground "cyan"))))
  '(font-lock-preprocessor-face ((t (:foreground "LightSteelBlue"))))
  '(font-lock-builtin-face ((t (:foreground "LightSteelBlue"))))
  ;; '(font-lock-comment-face ((t (:foreground "#5d5a58" :slant italic))))
  '(font-lock-comment-face ((t (:foreground "#5d5a58"))))
  '(font-lock-constant-face ((t (:foreground "Aquamarine"))))
  '(font-lock-function-name-face ((t (:foreground "DeepSkyBlue"))))
  '(font-lock-keyword-face ((t (:foreground "Cyan1"))))
  '(font-lock-string-face ((t (:foreground "LightSalmon"))))
  ;; '(font-lock-number-face ((t (:foreground "LightSalmon"))))
  `(font-lock-number-face ((,class (:foreground "VioletRed3")))) ;; ,plum-3
  '(font-lock-type-face ((t (:foreground "PaleGreen"))))
  '(font-lock-variable-name-face ((t (:foreground "LightGoldenrod"))))
  '(font-lock-warning-face ((t (:foreground "Pink" :weight bold))))
  '(secondary-selection ((t (:background "PaleVioletRed3" :distant-foreground "white"))))
  '(dired-directory ((t (:foreground "Skyblue2"))))
  '(highlight ((t (:background "gray20" :distant-foreground "gray50"))))
  '(button ((t (:background "black" :weight bold))))
  '(org-hide ((t (:foreground "black"))))
  '(ido-first-match ((t (:foreground "light green"))))))

(provide-theme 'dark-night-gray)
